config/routes.rb
Thunderpass::Application.routes.draw do
  root 'welcome#login'

  get "/auth/:provider/callback"  => "sessions#create_third_party", :as => :auth_callback
  get "/signout"                  => "sessions#destroy",            :as => :signout
  get "/signout_google"           => "sessions#signout_google",     :as => :signout_google
  get '/home'                     => 'welcome#new',                 :as => :home
  
  get  "/passes/report"             =>  "passes#report",              :as => :report
  resources :passes 
  resources :users
 end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations, dependent: :delete_all
  has_many :passes        , dependent: :delete_all
  belongs_to :school

  validates :email, uniqueness: {scope: :school}, presence: true
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :must_be_admin

  def index
    @users = User.where(school: current_user.user.school).order(:email)
    @users.reject!{|user| user.email === current_user.user.email}
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attribute(:email, params[:user][:email])
      redirect_to users_path, notice: "#{@user.email} was updated successfully."
    end
  end

  def create
    @user = User.new(email: params[:user][:email], school: current_user.user.school, admin: false)

    if @user.save
      redirect_to users_path, notice: "#{@user.email} was created successfully."
    else
      render new_user_path
    end
  end

  def destroy
    if user = User.find(params[:id])
      user.destroy
      redirect_to users_path
    end
  end

end

app/views/users/edit.html.haml
= render partial: 'shared/error_messages', locals: {model: @user}
%h3
  %center
    Edit user
%form.form-horizontal{role: "form", action: "#{user_path(@user.id)}", method: "POST", id: "update_user_form"}
  %input{:type=>"hidden", :name=>"authenticity_token", :value=>form_authenticity_token.to_s}
  %input{:type=>"hidden", :name=>"_method", :value=>"patch"}
  .form-group
    %label.col-lg-2.control-label{for: "inputEmail"} Email
    .col-lg-10
      %input#inputEmail.form-control.input-sm{placeholder: "Email address", type: "text", name: "user[email]", value: @user.email}
  .form-group
    .col-lg-offset-2.col-lg-10
      %button.btn.btn.btn-success.btn-default{type: "submit"} Update User
  %br
  .form-group
    .col-lg-offset-2.col-lg-10
      = link_to 'Back', users_path

:javascript
$(function() {
  $("#inputEmail").focus();      
});

app/views/users/index.html.haml
.panel.panel-default
  .panel-heading 
    %strong Users
  .panel-body
    %p 
      %strong
        = link_to "New User", new_user_path, class: "btn btn-sm btn-primary btn-success"
  %table.table.table-striped.table-bordered.table-hover
    %th
      Email
    %th
      %nbsp
    %th
      %nbsp
    - @users.each do |user|
      %tr
        %td
          #{user.email}  
        %td
          = button_to('Edit', edit_user_path(user), method: :get, class: "btn btn-sm btn-primary btn-info")
        %td
          = button_to('Delete', user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user ? Deleting the user will delete all passes created by this user."},class: "btn btn-sm btn-primary btn-warning")


:javascript
$(function(){
    $(".navbar-nav > li").removeClass('active');
    $('#admin_tab').addClass('active');
});      

app/views/users/new.html.haml
= render partial: 'shared/error_messages', locals: {model: @user}
%h3
  %center
    Add a new user
%form.form-horizontal{role: "form", action: "#{users_path}", method: "POST", id: "new_user_form"}
  %input{:type=>"hidden", :name=>"authenticity_token", :value=>form_authenticity_token.to_s}
  .form-group
    %label.col-lg-2.control-label{for: "inputEmail"} Email
    .col-lg-10
      %input#inputEmail.form-control.input-sm{placeholder: "Email address", type: "text", name: "user[email]", value: @user.email}
  .form-group
    .col-lg-offset-2.col-lg-10
      %button.btn.btn.btn-success.btn-default{type: "submit"} Create User
  %br
  .form-group
    .col-lg-offset-2.col-lg-10
      = link_to 'Back', users_path

:javascript
$(function() {
  $("#inputEmail").focus();      
});