config/routes.rb
Thunderpass::Application.routes.draw do
  root 'welcome#login'

  get "/auth/:provider/callback"  => "sessions#create_third_party", :as => :auth_callback
  get "/signout"                  => "sessions#destroy",            :as => :signout
  get "/signout_google"           => "sessions#signout_google",     :as => :signout_google
  get '/home'                     => 'welcome#new',                 :as => :home
  
  get  "/passes/report"             =>  "passes#report",              :as => :report
  resources :passes 
  resources :users
 end

app/views/shared/_error_messages.html.haml
- if model && model.errors && model.errors.size > 0
  .alert.alert-danger.alert-dismissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
    %strong Please correct the following:
    - model.errors.full_messages.each do |message|
      %br
      #{message}

  

app/views/shared/_flash.html.haml
- if flash[:alert]
  .alert.alert-danger.alert-dismissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
    %strong Warning!
    = flash[:alert]

- if flash[:notice]
  .alert.alert-success.alert-dismissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
    %strong
      .container
        = flash[:notice]

app/views/shared/_tabs.html.haml
%h1.text-center
  = school_nickname
.bs-docs-section.clearfix
  .row
    .col-lg-12
      .bs-example
        .navbar.navbar-inverse
          .container
            .navbar-header
              %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
            .navbar-collapse.collapse.navbar-responsive-collapse.navbar-inverse
              %ul.nav.navbar-nav
                %li.active
                  = link_to 'Home', home_url
                %li{id: 'view_passes_tab'}
                  = link_to 'Today\'s Passes', passes_path(order_by: :departed_at, asc_desc: :desc)
                %li{id: 'report_tab'}
                  = link_to 'Reports', report_path(order_by: :pass_date, asc_desc: :desc)
                - if current_user && current_user.user.admin?
                  %li.dropdown{id: 'admin_tab'}
                    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                      Admin
                      %b.caret
                    %ul.dropdown-menu
                      %li
                        = link_to "Users", users_path
              %ul.nav.navbar-nav.navbar-right
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    #{current_user.first_name} #{current_user.last_name}
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "Sign out", signout_path
                    %li
                      = link_to "Sign out of Google", signout_google_path
                    %li.divider
                    %li
                      %a{:href => "#"} Profile